:url-setup: docs/setup.asciidoc
:url-background: docs/background-information
:url-implementation: docs/implementation

# MIDI Project

This repository contains all information regarding the MIDI project.
This includes

* Some starter code
* Tests
* Documentation
* Configuration settings

== How To Get Started

. Start by going through the link:{url-setup}[setup instructions].
  Make sure to go through every step.
  If you have a problem due to not following these instructions correctly, the only help from me you will get is a link to this page.
. Skim through the link:{url-background}[background information] to get an idea of what is available.
  While certainly allowed, it is of little use to read this information thoroughly now.
  By the time you will need it, you will have forgotten most of it.
  The purpose of this background information is that you look it up whenever you need it, which is why you need to be aware of which topics are considered.
. Start going through the link:{url-implementation}[implementation steps] in order.
  Include the corresponding tests, create the necessary files and write code.
  Only proceed to the next step when everything compiles and all tests pass.

== Important Links

* link:{url-setup}[Setup Instructions]
* link:{url-background}[Background Information]
* link:{url-implementation}[Implementation steps]
* https://github.com/UCLeuvenLimburg/midihelper[Python Helper Script] which can help you with debugging.
* http://files.leone.ucll.be/midi-samples.zip[Sample MIDI files and corresponding visualizations]
